### ISSUE TITLE
Testing with React components

### ISSUE THREAD

**Issue by reintroducing** [timoxley/offset#12]
Hello Tim,
I'm using document-offset in a react component (a Tooltip that's inside of another component) and it works great.  My problem arises when I write a unit test for this setup.  I'm rendering the parent component into the document  using TestUtils.renderIntoDocument but I'm getting an error that top is undefined from that component. I track it back to my Tooltip component and documentOffset.  If I remove the following line, all works as expected and my tests pass:

`if (!withinElement(el, doc)) return`

I realize that this check is valid normally because you obviously want to pull the positions off of an element that actually lives in the document.  To make matters worse, I don't know entirely why this isnt working in my unit test, I just know that commenting out that line causes it to work.

This is a pretty specific use case, I understand, but wanted to run it by you in case it triggers anything in your mind as to why this may be happening or if you had any ideas on how I could/should proceed.  I'm pretty stumped to be honest and have spent a good portion of the day trying to circumvent it with no luck :\

Appreciate any help you can offer.

**Comment by reintroducing** [comment]
Ignore this, I figured out my component was double rendering and on the second render it didn't actually contain the tooltip as it was being cleared hence why it wasn't reporting as being part of the document :)

**Comment by timoxley** [comment]
:+1:
